export const SEO_CITIES = [
  "Mumbai",
  "Delhi",
  "Bangalore",
  "Hyderabad",
  "Ahmedabad",
  "Chennai",
  "Kolkata",
  "Surat",
  "Pune",
  "Jaipur",
  "Lucknow",
  "Kanpur",
  "Nagpur",
  "Indore",
  "Thane",
  "Bhopal",
  "Visakhapatnam",
  "Pimpri-Chinchwad",
  "Patna",
  "Vadodara",
  "Ghaziabad",
  "Ludhiana",
  "Agra",
  "Nashik",
  "Faridabad",
  "Meerut",
  "Rajkot",
  "Kalyan-Dombivli",
  "Vasai-Virar",
  "Varanasi",
  "Srinagar",
  "Aurangabad",
  "Dhanbad",
  "Amritsar",
  "Navi Mumbai",
  "Allahabad",
  "Ranchi",
  "Howrah",
  "Coimbatore",
  "Jabalpur",
  "Gwalior",
  "Vijayawada",
  "Jodhpur",
  "Madurai",
  "Raipur",
  "Kota",
  "Guwahati",
  "Chandigarh",
  "Solapur",
  "Hubli-Dharwad",
  "Bareilly",
  "Moradabad",
  "Mysore",
  "Tiruppur",
  "Gurgaon",
  "Aligarh",
  "Jalandhar",
  "Tiruchirappalli",
  "Bhubaneswar",
  "Salem",
  "Mira-Bhayandar",
  "Thiruvananthapuram",
  "Bhiwandi",
  "Saharanpur",
  "Guntur",
  "Amravati",
  "Bikaner",
  "Noida",
  "Jamshedpur",
  "Bhilai",
  "Cuttack",
  "Firozabad",
  "Kochi",
  "Bhavnagar",
  "Dehradun",
  "Asansol",
  "Nanded",
  "Kolhapur",
  "Ajmer",
  "Gulbarga",
  "Jamnagar",
  "Ujjain",
  "Loni",
  "Siliguri",
  "Jhansi",
  "Ulhasnagar",
  "Jammu",
  "Sangli-Miraj",
  "Mangalore",
  "Erode",
  "Belgaum",
  "Ambattur",
  "Tirunelveli",
  "Malegaon",
  "Gaya",
  "Jalgaon",
  "Udaipur",
  "Maheshtala",
  "Davanagere",
  "Kozhikode",
  "Akola"
];

export const SEO_KEYWORDS = {
  modifiers: ["Best", "Top", "Cheap", "Luxury", "Budget", "Verified", "Affordable", "Popular"],
  longTail: [
    "near me",
    "with price",
    "with photos",
    "reviews and ratings",
    "contact number",
    "for wedding",
    "for birthday party",
    "under 500"
  ]
};

export const SEO_CATEGORIES = [
  { slug: "banquet-halls", name: "Banquet Halls", title: "Banquet Halls" },
  { slug: "wedding-venues", name: "Wedding Venues", title: "Wedding Venues" },
  { slug: "birthday-party-venues", name: "Birthday Party Venues", title: "Birthday Party Venues" },
  { slug: "corporate-event-venues", name: "Corporate Event Venues", title: "Corporate Event Venues" },
  { slug: "party-lawns", name: "Party Lawns", title: "Party Lawns" },
  { slug: "resorts", name: "Resorts", title: "Resorts" },
  { slug: "catering-services", name: "Catering Services", title: "Caterers" },
  { slug: "event-planners", name: "Event Planners", title: "Event Planners" },
  { slug: "decorators", name: "Decorators", title: "Decorators" },
  { slug: "djs", name: "DJs", title: "DJs" }
];
